[package]
name = "proksi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "proksify"
path = "./src/proksify.rs"

[[bin]]
name = "proksi"
path = "./src/proksi.rs"

[dependencies]
socks-rs = { path = "./socks-rs" }

[dependencies.tokio]
version = "1.23.0"
default-features = false
features = [
    "net",
    "io-util",
    "rt-multi-thread",
    "macros"
]

[dev-dependencies.tokio]
version = "1.23.0"
features = [ "time", "process" ]

[workspace]
members = [
    "socks-rs"
]